/**
 * 
 */
package com.honda.cart2.batch.dao;


/**
 * @author vcc47494
 *
 */
public interface ACCProcessingBatchSQLIF {


	public static final String FETCH_PARAMS_FOR_PROCESSING = "SELECT * FROM --CART_SCHEMA--.FCASD1 ASD JOIN --CART_SCHEMA--.FCASM1 ASM ON ASD.SEQ_NO=ASM.SEQ_NO " +
			" WHERE ASD.SEQ_NO = (SELECT SEQ_NO from --CART_SCHEMA--.FCASD1 WHERE STATUS = ? ORDER BY MODIFIED_TSTP FETCH FIRST 1 ROWS ONLY)"; 

	public static final String UPDATE_STATUS_IN_FCADS1 = "UPDATE --CART_SCHEMA--.FCASD1 SET STATUS = ? WHERE SEQ_NO=? ";
	/**
	 * Fetches Engine, Mission and Differential based on the Frame and Event. 
	 * 1st half fetching the Base events data and 2nd half for fetching current events data.
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_FEMD_SQL = " SELECT TGT_ENG_FR_MOD_CDE, TGT_ENG_FR_TY_CODE, TGT_ENGFR_OPT_CODE, " +
			" TGT_MIS_FR_MOD_CDE, TGT_MIS_FR_TY_CODE, TGT_MISFR_OPT_CODE, " +
			" TGT_DIF_FR_MOD_CDE, TGT_DIF_FR_TY_CODE, TGT_DIFFR_OPT_CODE,'B' AS EVENT FROM --CART_SCHEMA--.FCEFM1 WHERE PH_COST_EVENT_NAME = :baseEventName " +
			" AND EVENT_REV_NO = :baseEventRev AND TGT_MODEL_DEV_CODE = :baseTargetModel and MTC_TYPE = :baseType AND MTC_OPTION = :baseOption " +
			" UNION ALL " +
			" SELECT TGT_ENG_FR_MOD_CDE, TGT_ENG_FR_TY_CODE, TGT_ENGFR_OPT_CODE, TGT_MIS_FR_MOD_CDE, TGT_MIS_FR_TY_CODE, TGT_MISFR_OPT_CODE, " +
			" TGT_DIF_FR_MOD_CDE, TGT_DIF_FR_TY_CODE, TGT_DIFFR_OPT_CODE,'C' AS EVENT FROM --CART_SCHEMA--.FCEFM1 WHERE PH_COST_EVENT_NAME = :currentEventName " +
			" AND EVENT_REV_NO = :currentEventRev AND TGT_MODEL_DEV_CODE = :currentTargetModel and MTC_TYPE = :currentType AND MTC_OPTION = :currentOption ";
	
	/**
	 * This query fetches Part Details for an Event.
	 */
	//Query is changed to fetch SHIP_TO_CODE from EPA1 table as there were two same records present in EPA1 except for SHIP_TO_CODE difference. Inorder to sum up their quantity below change is made
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_EVENT_PART_LEVEL_DETAILS = " SELECT DISTINCT DATA_MAINT_TSTP,PROC_SECT_CODE, SUPPLIER_NO, SUPPLIER_NAME," +
			"PLANT_LOC_CODE, PART_SECTION_CODE, MODEL_CAT_CODE,SHARE_RATE_PERCENT, SUM(PART_QTY) AS PART_QTY," +
			" PART_COLOR_CODE, " +
			" PART_NO, BASIC_PART_NAME," +
			"TGT_MODEL_DEV_CODE, MTC_TYPE,TGT_ENG_FR_MOD_CDE, TGT_ENG_FR_TY_CODE,TGT_MIS_FR_MOD_CDE, TGT_MIS_FR_TY_CODE," +
			"TGT_DIF_FR_MOD_CDE, TGT_DIF_FR_TY_CODE,COST_CHANGE_AMT, COST_CHANGE_AMT_JPY, COST_CHANGE_CODE, COST_CHG_CAT_CODE,COST_BEG_EFF_DATE,ACT_QUOTE_EFF_DATE" +
			" FROM(" +
			"SELECT DISTINCT EPC1.DATA_MAINT_TSTP, " +//DATA_MAINT_TSTP added in order to handle same MCC/BC/DCC/GCC/TCC for the same part record.
			" EPM1.PROC_SECT_CODE, EPA1.SUPPLIER_NO, SM1.SUPPLIER_NAME, " + //SM1.SUPPLIER_LOC_CODE, "+//check if Supp loc have any significance else remove - Answer not required hence removed.
			" EPA1.PLANT_LOC_CODE, EPA1.PART_SECTION_CODE, " +
			" EPA1.MODEL_CAT_CODE, " +
			" EPA1.SHARE_RATE_PERCENT, EPA1.PART_QTY, EPA1.PART_NO, BNM1.BASIC_PART_NAME, " +
			" EPA1.PART_COLOR_CODE, " +
			" EFM1.TGT_MODEL_DEV_CODE, EFM1.MTC_TYPE, " +
			" EFM1.TGT_ENG_FR_MOD_CDE, EFM1.TGT_ENG_FR_TY_CODE, " +
			" EFM1.TGT_MIS_FR_MOD_CDE, EFM1.TGT_MIS_FR_TY_CODE, " +
			" EFM1.TGT_DIF_FR_MOD_CDE, EFM1.TGT_DIF_FR_TY_CODE, " +
			" EPC1.COST_CHANGE_AMT, EPC1.COST_CHANGE_AMT_JPY, EPC1.COST_CHANGE_CODE, EPC1.COST_CHG_CAT_CODE,EPC1.COST_BEG_EFF_DATE,EPC1.ACT_QUOTE_EFF_DATE, EPA1.SHIP_TO_CODE" +
			" FROM " +
			" --CART_SCHEMA--.FCEFM1 EFM1, --CART_SCHEMA--.FCEPC1 EPC1, --CART_SCHEMA--.FCEPM1 EPM1, --CART_SCHEMA--.FCEPA1 EPA1 " +
			" LEFT OUTER JOIN --TIX_SCHEMA--.TIBNM1 BNM1 ON BNM1.TGT_BASIC_PART_NO = EPA1.PART_NO " +
			" LEFT OUTER JOIN --PUR_SCHEMA--.PUOSM1 SM1 ON SM1.SUPPLIER_NO=EPA1.SUPPLIER_NO " +
			" WHERE " +
			" ( " +
			" EPA1.PH_COST_EVENT_NAME = :eventName AND EPA1.EVENT_REV_NO = :eventRev " +
			" AND EPM1.PROC_SECT_CODE  BETWEEN :procSectionFrom  AND :procSectionTo " +
			" AND EPC1.ISO_CURRENCY_CODE  = :currency " + 
			" AND EPC1.COST_CHG_CAT_CODE  IN  ('BC', @MCCCodes@ ) " +
			" AND ( EFM1.TGT_MODEL_DEV_CODE, EFM1.MTC_TYPE, EFM1.MTC_OPTION ) IN " +
			" ( @FrameMTOs@ ) " +
			" AND " +
			" ( " +
			" ( EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_MODEL_DEV_CODE AND EPA1.MTC_TYPE = EFM1.MTC_TYPE AND EPA1.MODEL_CAT_CODE='F') " +
			" OR ( EPA1.MTC_TYPE = EFM1.TGT_ENG_FR_TY_CODE AND EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_ENG_FR_MOD_CDE AND EPA1.MODEL_CAT_CODE='E') " +
			" OR ( EPA1.MTC_TYPE = EFM1.TGT_MIS_FR_TY_CODE AND EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_MIS_FR_MOD_CDE AND EPA1.MODEL_CAT_CODE='M') " +
			" OR ( EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_DIF_FR_MOD_CDE AND EPA1.MTC_TYPE = EFM1.TGT_DIF_FR_TY_CODE AND EPA1.MODEL_CAT_CODE='D') " +
			" ) " +
			" ) AND " +
			" EPA1.PH_COST_EVENT_NAME = EPM1.PH_COST_EVENT_NAME AND EPA1.EVENT_REV_NO = EPM1.EVENT_REV_NO " +
			" AND EPA1.PART_NO = EPM1.PART_NO AND  EPA1.PART_COLOR_CODE = EPM1.PART_COLOR_CODE " +
			" AND EPC1.PH_COST_EVENT_NAME = EPA1.PH_COST_EVENT_NAME AND EPC1.EVENT_REV_NO = EPA1.EVENT_REV_NO " +
			" AND EPC1.PART_NO = EPA1.PART_NO AND EPC1.PART_COLOR_CODE = EPA1.PART_COLOR_CODE " +
			" AND EPC1.PLANT_LOC_CODE = EPA1.PLANT_LOC_CODE AND EPA1.SUPPLIER_NO = EPM1.SUPPLIER_NO " +
			" AND EPA1.SUPPLIER_NO = EPC1.SUPPLIER_NO " +
			" AND EPA1.PH_COST_EVENT_NAME = EFM1.PH_COST_EVENT_NAME AND EPA1.EVENT_REV_NO = EFM1.EVENT_REV_NO " +
			/*" AND ( " +//Committed as the condition seems redundant line 152
			" EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_MODEL_DEV_CODE " +
			" OR EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_ENG_FR_MOD_CDE " +
			" OR EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_MIS_FR_MOD_CDE" +
			" OR EPA1.TGT_MODEL_DEV_CODE = EFM1.TGT_DIF_FR_MOD_CDE " +
			" ) " +
			" AND ( " +
			" EPA1.MTC_TYPE = EFM1.MTC_TYPE " +
			" OR EPA1.MTC_TYPE = EFM1.TGT_ENG_FR_TY_CODE " +
			" OR EPA1.MTC_TYPE = EFM1.TGT_MIS_FR_TY_CODE " +
			" OR EPA1.MTC_TYPE = EFM1.TGT_DIF_FR_TY_CODE " +
			" ) " +*/
			" AND EPA1.MTC_OPTION = EFM1.MTC_OPTION " +
			//" AND EAM1.EVNT_CTRL_RPT_CODE = ECM1.EVNT_CTRL_RPT_CODE " + //used for Budget Control
			//" AND ECM1.TGT_MODEL_DEV_CODE = EFM1.TGT_MODEL_DEV_CODE " +
			//" AND ECM1.MTC_OPTION = EFM1.MTC_OPTION AND EFM1.MTC_TYPE = ECM1.MTC_TYPE " +
			//" AND EPA1.SUPPLIER_NO = SM1.SUPPLIER_NO " +
			" AND EPA1.SUPPLIER_NO --CONDITION_BASED_ON_CURRENCY-- 'JN9999' " // AND EPA1.PART_NO  IN ('61300HL5 E700') "
			// + " AND EPA1.SHARE_RATE_PERCENT <> 0 AND EPA1.PART_QTY <>0 "//removed this condition as if the SR and qty was non zero and ACC was generated and approved, after which it was zeroed then the record was not fetched hence not deleted from ACC1 table.
			+ " ) DATA " +//Added these 0 conditions for Share rate and Qty as the corresponding non zero record should be shown as part added/dropped
			" GROUP BY DATA_MAINT_TSTP,PROC_SECT_CODE, SUPPLIER_NO, SUPPLIER_NAME,PLANT_LOC_CODE, PART_SECTION_CODE, MODEL_CAT_CODE," +
			" SHARE_RATE_PERCENT,PART_COLOR_CODE, PART_NO, BASIC_PART_NAME,TGT_MODEL_DEV_CODE, MTC_TYPE,TGT_ENG_FR_MOD_CDE, TGT_ENG_FR_TY_CODE," +
			" TGT_MIS_FR_MOD_CDE, TGT_MIS_FR_TY_CODE,TGT_DIF_FR_MOD_CDE, TGT_DIF_FR_TY_CODE," +
			" COST_CHANGE_AMT, COST_CHANGE_AMT_JPY, COST_CHANGE_CODE, COST_CHG_CAT_CODE, COST_BEG_EFF_DATE, ACT_QUOTE_EFF_DATE " +
			" ORDER BY PROC_SECT_CODE, PART_NO, SUPPLIER_NO, PART_QTY, PART_SECTION_CODE, MODEL_CAT_CODE,PLANT_LOC_CODE, SHARE_RATE_PERCENT," +
			" PART_COLOR_CODE, " +
			" TGT_ENG_FR_MOD_CDE DESC,TGT_MIS_FR_MOD_CDE DESC, TGT_DIF_FR_MOD_CDE DESC WITH UR" ;
	
	/**
	 * Query to fetch ACC data for Exact Match
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_EXACT_MATCH_ACC_DATA = " SELECT " +
			" ACC.RULE_ID, ACC.APP_COST_CHANGE_CODE, ACC.ACC_AMOUNT, ACC.ACC_STATUS, ACC.ACC_RULE_PART_CHAR_MATCH, " +
			" ACC.PART_DISTINGUISHING_REASON, ACC.EFFECTIVE_DATE, ACC.MODIFIED_BY, ACC.MODIFIED_TSTP, " +
			" ACC.ACC_COMMENTS, COD.CODE_DESC_TEXT, ACC.IS_BASE_OR_CURRENT_EVENT " +
			" FROM --CART_SCHEMA--.FCACC1 ACC " +
			" LEFT JOIN --CART_SCHEMA--.FCCOD1 COD ON ACC.ACC_COMMENTS=COD.CODE AND CODE_NAME='ACC_COMMENTS' " +
			" WHERE " +
			" ACC.BASE_EVENT_NAME=:baseEventName AND ACC.BASE_EVENT_REV_NO=:baseEventRev AND " +
			" ACC.CURR_EVENT_NAME=:currentEventName AND ACC.CURR_EVENT_REV_NO=:currentEventRev AND " +
			" ACC.MODEL_CAT_CODE=:modelCatCode AND ACC.PLANT_LOC_CODE=:plantLocCode AND " +
			" ACC.PART_NO_CURR=:partNumberCurrent AND ACC.PART_NO_BASE=:partNumberBase AND " +
			" ACC.SUPPLIER_NO_BASE=:baseSupplierNumber " +
			" AND BASE_TGT_MODEL_DEV_CODE=:baseTgtModelDevCode AND BASE_MTC_TYPE=:baseMTCType AND BASE_MTC_OPTION='' " +
			" AND BASE_TGT_ENG_MOD_DEV_CODE=:baseTgtModelDevCodeEngine AND BASE_ENG_MTC_TYPE=:baseMTCTypeEngine AND BASE_ENG_MTC_OPTION=''" +
			" AND BASE_TGT_MIS_MOD_DEV_CODE=:baseTgtModelDevCodeMission AND BASE_MIS_MTC_TYPE=:baseMTCTypeMission AND BASE_MIS_MTC_OPTION=''" +
			" AND BASE_TGT_DIF_MOD_DEV_CODE=:baseTgtModelDevCodeDiff AND BASE_DIF_MTC_TYPE=:baseMTCTypeDiff AND BASE_DIF_MTC_OPTION=''" +
			" AND CURR_TGT_MODEL_DEV_CODE=:currentTgtModelDevCode AND CURR_MTC_TYPE =:currentMTCType AND CURR_MTC_OPTION=''" +
			" AND CURR_TGT_ENG_MOD_DEV_CODE=:currentTgtModelDevCodeEngine AND CURR_ENG_MTC_TYPE=:currentMTCTypeEngine AND CURR_ENG_MTC_OPTION=''" +
			" AND CURR_TGT_MIS_MOD_DEV_CODE=:currentTgtModelDevCodeMission AND CURR_MIS_MTC_TYPE=:currentMTCTypeMission AND CURR_MIS_MTC_OPTION=''" +
			" AND CURR_TGT_DIF_MOD_DEV_CODE=:currentTgtModelDevCodeDiff AND CURR_DIF_MTC_TYPE=:currentMTCTypeDiff AND CURR_DIF_MTC_OPTION=''";
	
	/**
	 * Query to fetch ALL ACC for a part record on screen and All MTOs for maintaining the sequence required in each object of ACC Data.
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_ALL_ACC_FORAROW = " SELECT " +
			" DISTINCT ACC.RULE_ID, MAR.RULE_DESC_TEXT, ACC.APP_COST_CHANGE_CODE, ACC.ACC_RULE_PART_CHAR_MATCH, " +
			" ACC.EFFECTIVE_DATE, ACC.ACC_STATUS, ACC.ACC_COMMENTS, COD.CODE_DESC_TEXT, ACC.IS_BASE_OR_CURRENT_EVENT "+//, ACC.MODIFIED_TSTP " +
			" FROM --CART_SCHEMA--.FCACC1 ACC " +
			" LEFT JOIN --CART_SCHEMA--.FCCOD1 COD ON ACC.ACC_COMMENTS=COD.CODE AND CODE_NAME='ACC_COMMENTS' " +
			" LEFT JOIN --CART_SCHEMA--.FCMAR1 MAR ON ACC.RULE_ID=MAR.RULE_ID " +
			" --CONDITION_TO_COMPARE_BASE_MTO_WITH_EPA--" +
			" --CONDITION_TO_COMPARE_CURRENT_MTO_WITH_EPA--" +
			" WHERE " +
			" ACC.BASE_EVENT_NAME=:baseEventName AND ACC.BASE_EVENT_REV_NO=:baseEventRev AND " +
			" ACC.CURR_EVENT_NAME=:currentEventName AND ACC.CURR_EVENT_REV_NO=:currentEventRev AND " +
			" ACC.MODEL_CAT_CODE=:modelCatCode AND ACC.PLANT_LOC_CODE=:plantLocCode AND " +
			" ACC.PART_NO_CURR=:partNumberCurrent AND ACC.PART_NO_BASE=:partNumberBase AND " +
			" ACC.SUPPLIER_NO_BASE=:baseSupplierNumber  AND ACC.PART_SECTION_CODE=:partSectCode " +
			" AND (ACC.CURR_TGT_MODEL_DEV_CODE, ACC.CURR_MTC_TYPE,ACC.BASE_TGT_MODEL_DEV_CODE, ACC.BASE_MTC_TYPE," +
			" ACC.CURR_TGT_ENG_MOD_DEV_CODE, ACC.CURR_ENG_MTC_TYPE, ACC.BASE_TGT_ENG_MOD_DEV_CODE, ACC.BASE_ENG_MTC_TYPE," +
			" ACC.CURR_TGT_MIS_MOD_DEV_CODE, ACC.CURR_MIS_MTC_TYPE, ACC.BASE_TGT_MIS_MOD_DEV_CODE, ACC.BASE_MIS_MTC_TYPE," +
			" ACC.CURR_TGT_DIF_MOD_DEV_CODE, ACC.CURR_DIF_MTC_TYPE, ACC.BASE_TGT_DIF_MOD_DEV_CODE, ACC.BASE_DIF_MTC_TYPE) IN " +
			" ( @allScreenMTOs@ )" ;
	
	/**
	 * Conditional query to fetch data from EPA1 comparing BASE MTO
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_ALL_ACC_FORAROW_BASE_MTO_CONDITION = " JOIN --CART_SCHEMA--.FCEPA1 BASEEPA ON ACC.BASE_EVENT_NAME = BASEEPA.PH_COST_EVENT_NAME AND ACC.BASE_EVENT_REV_NO = BASEEPA.EVENT_REV_NO " +
			" AND ACC.MODEL_CAT_CODE = BASEEPA.MODEL_CAT_CODE AND ACC.PLANT_LOC_CODE = BASEEPA.PLANT_LOC_CODE " +
			" AND ACC.PART_NO_BASE = BASEEPA.PART_NO @Base_Design_Sect " +
			" AND --BASE_MTO_COMPARISON-- ";
	
	/**
	 * Conditional query to fetch data from EPA1 comparing CURRENT MTO
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_ALL_ACC_FORAROW_CURRENT_MTO_CONDITION = " JOIN --CART_SCHEMA--.FCEPA1 CURREPA ON ACC.CURR_EVENT_NAME = CURREPA.PH_COST_EVENT_NAME AND ACC.CURR_EVENT_REV_NO = CURREPA.EVENT_REV_NO " +
			" AND ACC.MODEL_CAT_CODE = CURREPA.MODEL_CAT_CODE AND ACC.PLANT_LOC_CODE = CURREPA.PLANT_LOC_CODE " +
			" AND ACC.PART_NO_CURR = CURREPA.PART_NO @Curr_Design_Sect " +
			" AND --CURR_MTO_COMPARISON-- ";
	
	/**
	 * Query to fetch ACC data for Un Match
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_UN_MATCH_ACC_DATA = " SELECT " +
			" ACC.RULE_ID, ACC.APP_COST_CHANGE_CODE, ACC.ACC_AMOUNT, ACC.ACC_STATUS, ACC.ACC_RULE_PART_CHAR_MATCH, " +
			" ACC.PART_DISTINGUISHING_REASON, ACC.EFFECTIVE_DATE, ACC.MODIFIED_BY, ACC.MODIFIED_TSTP, " +
			" ACC.ACC_COMMENTS, COD.CODE_DESC_TEXT, ACC.IS_BASE_OR_CURRENT_EVENT " +
			" FROM --CART_SCHEMA--.FCACC1 ACC " +
			" LEFT JOIN --CART_SCHEMA--.FCCOD1 COD ON ACC.ACC_COMMENTS=COD.CODE AND CODE_NAME='ACC_COMMENTS' " +
			" WHERE " +
			" ACC.BASE_EVENT_NAME=:baseEventName AND ACC.BASE_EVENT_REV_NO=:baseEventRev AND " +
			" ACC.CURR_EVENT_NAME=:currentEventName AND ACC.CURR_EVENT_REV_NO=:currentEventRev AND " +
			" ACC.MODEL_CAT_CODE=:modelCatCode AND ACC.PLANT_LOC_CODE=:plantLocCode AND " +
			" ACC.PART_NO_CURR=:partNumberCurrent AND ACC.PART_NO_BASE=:partNumberBase AND " +
			" ACC.SUPPLIER_NO_BASE=:baseSupplierNumber AND ACC.SUPPLIER_NO_CURR=:currentSupplierNumber " +
			" AND (ACC.PROC_SECT_CODE=:procSectCode OR ACC.PROC_SECT_CODE=:baseProcSectCode) AND ACC.PART_SECTION_CODE=:partSectCode "+
			" AND BASE_TGT_MODEL_DEV_CODE=:baseTgtModelDevCode AND BASE_MTC_TYPE=:baseMTCType AND BASE_MTC_OPTION='' " +
			" AND BASE_TGT_ENG_MOD_DEV_CODE=:baseTgtModelDevCodeEngine AND BASE_ENG_MTC_TYPE=:baseMTCTypeEngine AND BASE_ENG_MTC_OPTION=''" +
			" AND BASE_TGT_MIS_MOD_DEV_CODE=:baseTgtModelDevCodeMission AND BASE_MIS_MTC_TYPE=:baseMTCTypeMission AND BASE_MIS_MTC_OPTION=''" +
			" AND BASE_TGT_DIF_MOD_DEV_CODE=:baseTgtModelDevCodeDiff AND BASE_DIF_MTC_TYPE=:baseMTCTypeDiff AND BASE_DIF_MTC_OPTION=''" +
			" AND CURR_TGT_MODEL_DEV_CODE=:currentTgtModelDevCode AND CURR_MTC_TYPE =:currentMTCType AND CURR_MTC_OPTION=''" +
			" AND CURR_TGT_ENG_MOD_DEV_CODE=:currentTgtModelDevCodeEngine AND CURR_ENG_MTC_TYPE=:currentMTCTypeEngine AND CURR_ENG_MTC_OPTION=''" +
			" AND CURR_TGT_MIS_MOD_DEV_CODE=:currentTgtModelDevCodeMission AND CURR_MIS_MTC_TYPE=:currentMTCTypeMission AND CURR_MIS_MTC_OPTION=''" +
			" AND CURR_TGT_DIF_MOD_DEV_CODE=:currentTgtModelDevCodeDiff AND CURR_DIF_MTC_TYPE=:currentMTCTypeDiff AND CURR_DIF_MTC_OPTION=''" +
			" AND ACC.IS_BASE_OR_CURRENT_EVENT=:currOrBaseEvent";//CPT-357
	
	/**
	 * This query checks whether for an event a part have proc sect code change .
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_PROC_SECT_CODE_CHANGE = " SELECT EPM.PROC_SECT_CODE, EPM.SUPPLIER_NO, EPC.COST_CHG_CAT_CODE," +
			" EPC.COST_CHANGE_AMT, EPC.COST_CHANGE_AMT_JPY, EPA.PART_QTY, EPA.SHARE_RATE_PERCENT, EPA.PART_SECTION_CODE FROM --CART_SCHEMA--.FCEPM1 EPM " +
			" JOIN --CART_SCHEMA--.FCEPA1 EPA " +
			" ON EPM.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPA.SUPPLIER_NO" +
			" AND EPM.PART_NO = EPA.PART_NO " +
			" JOIN --CART_SCHEMA--.FCEPC1 EPC " +
			" ON EPM.PH_COST_EVENT_NAME = EPC.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPC.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPC.SUPPLIER_NO" +
			" AND EPM.PART_NO = EPC.PART_NO " +
			" WHERE EPM.PH_COST_EVENT_NAME=:eventName AND EPM.EVENT_REV_NO=:eventRev AND EPA.TGT_MODEL_DEV_CODE=:modelDevCode AND EPA.MTC_TYPE=:mtcType " +
			" AND EPA.MODEL_CAT_CODE=:modelCatCode AND EPA.SHARE_RATE_PERCENT <> 0 AND EPA.PART_QTY <>0" +//Added these 0 conditions for Share rate and Qty as the corresponding non zero record should be shown as part added/dropped
			//CPT-1089 start
			//" AND EPM.PART_NO=:partNumber AND EPM.PROC_SECT_CODE NOT BETWEEN :procSectionFrom  AND :procSectionTo AND EPM.SUPPLIER_NO  --CONDITION_BASED_ON_CURRENCY-- 'JN9999' ";//CPT-1033 - JN99999 only for reports with JPY currency
			" AND EPM.PART_NO=:partNumber AND EPM.PROC_SECT_CODE <> :procSection  AND EPM.SUPPLIER_NO  --CONDITION_BASED_ON_CURRENCY-- 'JN9999' ";//CPT-1033 - JN99999 only for reports with JPY currency
			//CPT-1089 end

	public static final String CHECK_EXACT_MATCH_AVAILABLE = " SELECT COUNT(*) AS COUNT FROM --CART_SCHEMA--.FCEPM1 EPM " +
	" JOIN --CART_SCHEMA--.FCEPA1 EPA " +
	" ON EPM.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPA.SUPPLIER_NO" +
	" AND EPM.PART_NO = EPA.PART_NO " +
	" JOIN --CART_SCHEMA--.FCEPC1 EPC " +
	" ON EPM.PH_COST_EVENT_NAME = EPC.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPC.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPC.SUPPLIER_NO" +
	" AND EPM.PART_NO = EPC.PART_NO " +
	" WHERE EPM.PH_COST_EVENT_NAME=:eventName AND EPM.EVENT_REV_NO=:eventRev AND EPA.TGT_MODEL_DEV_CODE=:modelDevCode AND EPA.MTC_TYPE=:mtcType " +
	" AND EPA.MODEL_CAT_CODE=:modelCatCode AND EPA.SHARE_RATE_PERCENT =:shareRate AND EPA.PART_QTY =:partQty " +//Added these 0 conditions for Share rate and Qty as the corresponding non zero record should be shown as part added/dropped
	" AND EPM.PART_NO=:partNumber AND EPM.PROC_SECT_CODE = :procSecCode AND EPM.SUPPLIER_NO = :suppNo AND EPA.PART_SECTION_CODE = :partSecCode ";

	//INC0726363  / CPT-357 - start - fetch only parts having cost change amount
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_PROC_SECT_CODE_CHANGE_ENTIRE_EVENT = " SELECT EPM.PROC_SECT_CODE, EPM.SUPPLIER_NO, EPA.PART_NO, " +
	" EPA.PART_QTY,  EPA.SHARE_RATE_PERCENT, EPC.COST_CHANGE_AMT_JPY, EPC.COST_CHG_CAT_CODE, EPC.COST_CHANGE_AMT FROM --CART_SCHEMA--.FCEPM1 EPM " +
	" JOIN --CART_SCHEMA--.FCEPA1 EPA " +
	" ON EPM.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPA.SUPPLIER_NO" +
	" AND EPM.PART_NO = EPA.PART_NO " +
	" JOIN --CART_SCHEMA--.FCEPC1 EPC " +
	" ON  EPC.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPC.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPC.SUPPLIER_NO = EPA.SUPPLIER_NO " + 
	" AND EPC.PART_NO = EPA.PART_NO " +
	" WHERE EPM.PH_COST_EVENT_NAME=:eventName AND EPM.EVENT_REV_NO=:eventRev AND EPA.TGT_MODEL_DEV_CODE=:modelDevCode AND EPA.MTC_TYPE=:mtcType " +
	" AND EPA.MODEL_CAT_CODE=:modelCatCode AND EPA.SHARE_RATE_PERCENT <> 0 AND EPA.PART_QTY <>0" +//Added these 0 conditions for Share rate and Qty as the corresponding non zero record should be shown as part added/dropped
	" AND EPM.PART_NO LIKE :partNumber AND EPC.COST_CHG_CAT_CODE IN ('BC','MCC') AND   EPC.COST_CHANGE_AMT <> '0.0000' " + // AND  --SUPPLIER_CONDITION-- " + 
	" ORDER BY PROC_SECT_CODE, PART_NO, SUPPLIER_NO, PART_QTY,  MODEL_CAT_CODE, SHARE_RATE_PERCENT ";
	
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_PROC_SECT_CODE_CHANGE_PARTIAL_MATCH = " SELECT EPM.PROC_SECT_CODE, EPM.SUPPLIER_NO FROM --CART_SCHEMA--.FCEPM1 EPM " +
	" JOIN --CART_SCHEMA--.FCEPA1 EPA " +
	" ON EPM.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPA.SUPPLIER_NO" +
	" AND EPM.PART_NO = EPA.PART_NO " +
	" WHERE EPM.PH_COST_EVENT_NAME=:eventName AND EPM.EVENT_REV_NO=:eventRev AND EPA.TGT_MODEL_DEV_CODE=:modelDevCode AND EPA.MTC_TYPE=:mtcType " +
	" AND EPA.MODEL_CAT_CODE=:modelCatCode AND EPA.SHARE_RATE_PERCENT <> 0 AND EPA.PART_QTY <>0" +//Added these 0 conditions for Share rate and Qty as the corresponding non zero record should be shown as part added/dropped
	" AND EPM.PART_NO LIKE :partNumber AND EPM.PROC_SECT_CODE NOT BETWEEN :procSectionFrom  AND :procSectionTo ";
	//INC0726363  / CPT-357 - end
	/**
	 * This query checks whether for an event a part have proc sect code change .
	 */
	public static final String ENTER_ACC_SUPP_MTO_CHECK_DESIGN_SECT_QTY_SHARERATE = " SELECT DISTINCT PART_SECTION_CODE, SHARE_RATE_PERCENT,PART_QTY " +
			" FROM --CART_SCHEMA--.FCEPM1 EPM " +
			" JOIN --CART_SCHEMA--.FCEPA1 EPA " +
			" ON EPM.PH_COST_EVENT_NAME = EPA.PH_COST_EVENT_NAME AND EPM.EVENT_REV_NO = EPA.EVENT_REV_NO AND EPM.SUPPLIER_NO = EPA.SUPPLIER_NO" +
			" AND EPM.PART_NO = EPA.PART_NO " +
			" WHERE EPM.PH_COST_EVENT_NAME=:eventName AND EPM.EVENT_REV_NO=:eventRev " +
			" AND EPA.TGT_MODEL_DEV_CODE=:modelDevCode AND EPA.MTC_TYPE=:mtcType " +
			" AND EPA.MODEL_CAT_CODE=:modelCatCode AND EPM.PART_NO=:partNumber" +
			" AND EPM.PROC_SECT_CODE =:procSection AND EPM.SUPPLIER_NO =:suppNumber ";
	
	/**
	 * Query to fetch ACC data for Proc Change and Added/dropped  Parts
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_PROC_CHANGE_ADDED_DROPPED_PARTS_ACC_DATA = " SELECT " +
			" ACC.RULE_ID, ACC.APP_COST_CHANGE_CODE, ACC.ACC_AMOUNT, ACC.ACC_STATUS, ACC.ACC_RULE_PART_CHAR_MATCH, " +
			" ACC.PART_DISTINGUISHING_REASON, ACC.EFFECTIVE_DATE, ACC.MODIFIED_BY, ACC.MODIFIED_TSTP, " +
			" ACC.ACC_COMMENTS, COD.CODE_DESC_TEXT, ACC.IS_BASE_OR_CURRENT_EVENT " +
			" FROM --CART_SCHEMA--.FCACC1 ACC " +
			" LEFT JOIN --CART_SCHEMA--.FCCOD1 COD ON ACC.ACC_COMMENTS=COD.CODE AND CODE_NAME='ACC_COMMENTS' " +
			" WHERE " +
			" ACC.BASE_EVENT_NAME=:baseEventName AND ACC.BASE_EVENT_REV_NO=:baseEventRev AND " +
			" ACC.CURR_EVENT_NAME=:currentEventName AND ACC.CURR_EVENT_REV_NO=:currentEventRev AND " +
			" ACC.MODEL_CAT_CODE=:modelCatCode AND ACC.PLANT_LOC_CODE=:plantLocCode AND " +
			" ACC.PART_NO_CURR=:partNumberCurrent AND ACC.PART_NO_BASE=:partNumberBase AND " +
			" ACC.SUPPLIER_NO_BASE=:baseSupplierNumber AND ACC.PART_SECTION_CODE=:partSectCode " +
			" AND ACC.PROC_SECT_CODE=:procSectCode " +
	        " AND COALESCE(TRIM(ACC.PART_COLOR_CODE), '') = :partColorCode " +
			" AND BASE_TGT_MODEL_DEV_CODE=:baseTgtModelDevCode AND BASE_MTC_TYPE=:baseMTCType AND BASE_MTC_OPTION='' " +
			" AND BASE_TGT_ENG_MOD_DEV_CODE=:baseTgtModelDevCodeEngine AND BASE_ENG_MTC_TYPE=:baseMTCTypeEngine AND BASE_ENG_MTC_OPTION=''" +
			" AND BASE_TGT_MIS_MOD_DEV_CODE=:baseTgtModelDevCodeMission AND BASE_MIS_MTC_TYPE=:baseMTCTypeMission AND BASE_MIS_MTC_OPTION=''" +
			" AND BASE_TGT_DIF_MOD_DEV_CODE=:baseTgtModelDevCodeDiff AND BASE_DIF_MTC_TYPE=:baseMTCTypeDiff AND BASE_DIF_MTC_OPTION=''" +
			" AND CURR_TGT_MODEL_DEV_CODE=:currentTgtModelDevCode AND CURR_MTC_TYPE =:currentMTCType AND CURR_MTC_OPTION=''" +
			" AND CURR_TGT_ENG_MOD_DEV_CODE=:currentTgtModelDevCodeEngine AND CURR_ENG_MTC_TYPE=:currentMTCTypeEngine AND CURR_ENG_MTC_OPTION=''" +
			" AND CURR_TGT_MIS_MOD_DEV_CODE=:currentTgtModelDevCodeMission AND CURR_MIS_MTC_TYPE=:currentMTCTypeMission AND CURR_MIS_MTC_OPTION=''" +
			" AND CURR_TGT_DIF_MOD_DEV_CODE=:currentTgtModelDevCodeDiff AND CURR_DIF_MTC_TYPE=:currentMTCTypeDiff AND CURR_DIF_MTC_OPTION=''";

	
	
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_PROC_CHANGE_ADDED_DROPPED_PARTS_ACC_DATA_CURRENT = " SELECT " +
	" ACC.RULE_ID, ACC.APP_COST_CHANGE_CODE, ACC.ACC_AMOUNT, ACC.ACC_STATUS, ACC.ACC_RULE_PART_CHAR_MATCH, " +
	" ACC.PART_DISTINGUISHING_REASON, ACC.EFFECTIVE_DATE, ACC.MODIFIED_BY, ACC.MODIFIED_TSTP, " +
	" ACC.ACC_COMMENTS, COD.CODE_DESC_TEXT, ACC.IS_BASE_OR_CURRENT_EVENT " +
	" FROM --CART_SCHEMA--.FCACC1 ACC " +
	" LEFT JOIN --CART_SCHEMA--.FCCOD1 COD ON ACC.ACC_COMMENTS=COD.CODE AND CODE_NAME='ACC_COMMENTS' " +
	" WHERE " +
	" ACC.BASE_EVENT_NAME=:baseEventName AND ACC.BASE_EVENT_REV_NO=:baseEventRev AND " +
	" ACC.CURR_EVENT_NAME=:currentEventName AND ACC.CURR_EVENT_REV_NO=:currentEventRev AND " +
	" ACC.MODEL_CAT_CODE=:modelCatCode AND ACC.PLANT_LOC_CODE=:plantLocCode AND " +
	" ACC.PART_NO_CURR=:partNumberCurrent AND ACC.PART_NO_BASE=:partNumberBase AND " +
	" ACC.SUPPLIER_NO_CURR=:baseSupplierNumber AND ACC.PART_SECTION_CODE=:partSectCode " +
	" AND ACC.PROC_SECT_CODE=:procSectCode " +
	" AND COALESCE(TRIM(ACC.PART_COLOR_CODE), '') = :partColorCode " +
	" AND BASE_TGT_MODEL_DEV_CODE=:baseTgtModelDevCode AND BASE_MTC_TYPE=:baseMTCType AND BASE_MTC_OPTION='' " +
	" AND BASE_TGT_ENG_MOD_DEV_CODE=:baseTgtModelDevCodeEngine AND BASE_ENG_MTC_TYPE=:baseMTCTypeEngine AND BASE_ENG_MTC_OPTION=''" +
	" AND BASE_TGT_MIS_MOD_DEV_CODE=:baseTgtModelDevCodeMission AND BASE_MIS_MTC_TYPE=:baseMTCTypeMission AND BASE_MIS_MTC_OPTION=''" +
	" AND BASE_TGT_DIF_MOD_DEV_CODE=:baseTgtModelDevCodeDiff AND BASE_DIF_MTC_TYPE=:baseMTCTypeDiff AND BASE_DIF_MTC_OPTION=''" +
	" AND CURR_TGT_MODEL_DEV_CODE=:currentTgtModelDevCode AND CURR_MTC_TYPE =:currentMTCType AND CURR_MTC_OPTION=''" +
	" AND CURR_TGT_ENG_MOD_DEV_CODE=:currentTgtModelDevCodeEngine AND CURR_ENG_MTC_TYPE=:currentMTCTypeEngine AND CURR_ENG_MTC_OPTION=''" +
	" AND CURR_TGT_MIS_MOD_DEV_CODE=:currentTgtModelDevCodeMission AND CURR_MIS_MTC_TYPE=:currentMTCTypeMission AND CURR_MIS_MTC_OPTION=''" +
	" AND CURR_TGT_DIF_MOD_DEV_CODE=:currentTgtModelDevCodeDiff AND CURR_DIF_MTC_TYPE=:currentMTCTypeDiff AND CURR_DIF_MTC_OPTION=''";

	/**
	 * This query fetches the ACC Code.
	 */
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_ACC_CODE_SQL = 
			" SELECT CODE FROM --CART_SCHEMA--.FCCOD1 WHERE CODE_NAME like '%ACC_CODE%' ";
	
	public static final String ENTER_ACC_SUPP_MTO_SUMMARY_ACC_RULE_SQL = " SELECT RULE_ID, APP_COST_CHANGE_CODE FROM --CART_SCHEMA--.FCMAR1 " +
			" WHERE APP_COST_CHANGE_CODE IN (SELECT CODE FROM --CART_SCHEMA--.FCCOD1 WHERE CODE_NAME like '%ACC_CODE%') AND STATUS='ENABLED' ";

	public static final String FIND_ACTIVE_RULES = "SELECT * FROM --CART_SCHEMA--.FCMAR1 where STATUS ='ENABLED'";
	
	public static final String FIND_INHOUSE_SUPPLIER = "SELECT CODE FROM --CART_SCHEMA--.FCCOD1 WHERE CODE_NAME LIKE '%IN_HOUSE_SUPP%'";
	
	public static final String INSERT_ACC2_DATA = " INSERT INTO --CART_SCHEMA--.FCACC2( "+
		" CURR_EVENT_NAME, CURR_EVENT_REV_NO, BASE_EVENT_NAME, BASE_EVENT_REV_NO, PROC_GRP, " +
		" SUPPLIER_NO, SUPPLIER_NO_BASE_CURRENT, SUPPLIER_NAME, PLANT_LOC_CODE, DESIGN_SECTION_CODE, " +
		" MODEL_CAT_CODE, SHARE_RATE, QTY, PART_NO, PART_NO_BASE_CURRENT, " +
		" PART_NAME, PART_ACC_INDICATOR, PREVIOUS_COST, CURRENT_COST, DIFFERENCE_COST, " +
		" MCC_COST, BALANCE_COST, ACC_COST, ACC_CODE, ACC_STATUS, " +
		" RULE_ID, RULE_PART_CHAR_MATCH, EFFECTIVE_DATE,  " +
		" MODIFIED_BY_DATA, MODIFIED_BY_TSTP_DATA, BASE_OR_CURRENT_EVENT, BASE_OR_CURRENT_EVENT_ORIG, BOM_CHANGE_IMPACT_ON_ACC, " +
		" ACC_COMMENT_CODE, ACC_COMMENT_DESC, ACC_COMMENT_NOTE, " +
		" BASE_TGT_MODEL_DEV_CODE, BASE_MTC_TYPE, BASE_MTC_OPTION, CURR_TGT_MODEL_DEV_CODE, CURR_MTC_TYPE, CURR_MTC_OPTION, " +
		" BASE_TGT_ENG_MOD_DEV_CODE, BASE_ENG_MTC_TYPE, BASE_ENG_MTC_OPTION, CURR_TGT_ENG_MOD_DEV_CODE, CURR_ENG_MTC_TYPE, CURR_ENG_MTC_OPTION, " +
		" BASE_TGT_MIS_MOD_DEV_CODE, BASE_MIS_MTC_TYPE, BASE_MIS_MTC_OPTION,  CURR_TGT_MIS_MOD_DEV_CODE, CURR_MIS_MTC_TYPE, CURR_MIS_MTC_OPTION," +
		" BASE_TGT_DIF_MOD_DEV_CODE, BASE_DIF_MTC_TYPE, BASE_DIF_MTC_OPTION, CURR_TGT_DIF_MOD_DEV_CODE, CURR_DIF_MTC_TYPE, CURR_DIF_MTC_OPTION, " +
		" CREATED_BY, CREATED_TSTP, MODIFIED_BY, MODIFIED_TSTP, PART_COLOR_CODE " +
		" )"
		+ " VALUES "
		+ " (?,?,?,?,?,"
		+ "	?,?,?,?,?,"
		+ "	?,?,?,?,?,"
		+ "	?,?,?,?,?,"
		+ " ?,?,?,?,?,"
		+ "	?,?,?,"
		+ "	?,?,?,?,?,"
		+ "	?,?,?,"
		+ "	?,?,?,?,?,?,"
		+ "	?,?,?,?,?,?,"
		+ "	?,?,?,?,?,?,"
		+ " ?,?,?,?,?,?,"
		+ "	'ACC_BATCH', CURRENT TIMESTAMP , 'ACC_BATCH', CURRENT TIMESTAMP, ? ) ";
		
	public static final String DELETE_ACC2_DATA = " DELETE FROM --CART_SCHEMA--.FCACC2 WHERE CURR_EVENT_NAME=? AND CURR_EVENT_REV_NO=? " +
			" AND BASE_EVENT_NAME=? AND BASE_EVENT_REV_NO=? " +
			" AND PROC_GRP IN(--PROC_GRPS--) AND " +
			"(BASE_TGT_MODEL_DEV_CODE,BASE_MTC_TYPE,BASE_MTC_OPTION,CURR_TGT_MODEL_DEV_CODE,CURR_MTC_TYPE,CURR_MTC_OPTION," +
			" BASE_TGT_ENG_MOD_DEV_CODE,BASE_ENG_MTC_TYPE,BASE_ENG_MTC_OPTION,CURR_TGT_ENG_MOD_DEV_CODE,CURR_ENG_MTC_TYPE,CURR_ENG_MTC_OPTION," +
			" BASE_TGT_MIS_MOD_DEV_CODE,BASE_MIS_MTC_TYPE,BASE_MIS_MTC_OPTION,CURR_TGT_MIS_MOD_DEV_CODE,CURR_MIS_MTC_TYPE,CURR_MIS_MTC_OPTION," +
			" BASE_TGT_DIF_MOD_DEV_CODE,BASE_DIF_MTC_TYPE,BASE_DIF_MTC_OPTION,CURR_TGT_DIF_MOD_DEV_CODE,CURR_DIF_MTC_TYPE,CURR_DIF_MTC_OPTION) " +
			" IN (--STR_MTO--) ";
	
	public static final String GET_PROC_GROUP_BET_SEL_PROC_GRPS="SELECT CODE FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PROC_SECT_CODE' AND CODE BETWEEN ? and ?";
	
	public static final String GET_MAIL_ID_LOGGED_IN_USER = "SELECT USER_EMAIL_ID FROM --CART_SCHEMA--.FCUSR1 WHERE UPPER(USER_LOGON_ID_NO) = ? OR UPPER(USER_GUID_NO) = ? ";
	
	public static final String FETCH_ACC_DEFINITION="SELECT SEQ_NO, STATUS, DESC_TEXT, CREATED_BY FROM --CART_SCHEMA--.FCASD1 WHERE SEQ_NO = ?";
	
}
